/* automatically generated by tools/bindgen-all-the-things */

#![allow(clippy::missing_safety_doc)]
#![allow(clippy::upper_case_acronyms)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

pub const GH_IOCTL_TYPE: u8 = 71u8;
pub const GH_MEM_ALLOW_READ: u32 = 1;
pub const GH_MEM_ALLOW_WRITE: u32 = 2;
pub const GH_MEM_ALLOW_EXEC: u32 = 4;
pub const GH_MEM_LENT: u32 = 8;
pub const GUNYAH_FUNCTION_NAME_SIZE: u32 = 32;
pub const GUNYAH_FUNCTION_MAX_ARG_SIZE: u32 = 1024;
pub const GH_IRQFD_LEVEL: u32 = 1;
pub const GH_IRQFD_DEASSIGN: u32 = 2;
pub const GH_IOEVENTFD_DATAMATCH: u32 = 1;
pub const GH_VM_EXIT_UNKNOWN: u32 = 0;
pub const GH_VM_EXIT_MMIO: u32 = 1;
pub type __le16 = u16;
pub type __be16 = u16;
pub type __le32 = u32;
pub type __be32 = u32;
pub type __le64 = u64;
pub type __be64 = u64;
pub type __sum16 = u16;
pub type __wsum = u32;
pub type __poll_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_userspace_memory_region {
    pub label: u32,
    pub flags: u32,
    pub guest_phys_addr: u64,
    pub memory_size: u64,
    pub userspace_addr: u64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_vm_dtb_config {
    pub gpa: u64,
    pub size: u64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_fn_vcpu_arg {
    pub vcpu_id: u32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_fn_irqfd_arg {
    pub fd: u32,
    pub label: u32,
    pub flags: u32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_fn_ioeventfd_arg {
    pub datamatch: u64,
    pub addr: u64,
    pub len: u32,
    pub fd: i32,
    pub flags: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gh_vm_function {
    pub name: [::std::os::raw::c_char; 32usize],
    pub __bindgen_anon_1: gh_vm_function__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gh_vm_function__bindgen_ty_1 {
    pub vcpu: gh_fn_vcpu_arg,
    pub irqfd: gh_fn_irqfd_arg,
    pub ioeventfd: gh_fn_ioeventfd_arg,
    pub data: [::std::os::raw::c_char; 1024usize],
}
impl Default for gh_vm_function__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gh_vm_function {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gh_vcpu_run {
    pub immediate_exit: u8,
    pub padding1: [u8; 7usize],
    pub exit_reason: u32,
    pub __bindgen_anon_1: gh_vcpu_run__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gh_vcpu_run__bindgen_ty_1 {
    pub mmio: gh_vcpu_run__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_vcpu_run__bindgen_ty_1__bindgen_ty_1 {
    pub phys_addr: u64,
    pub data: [u8; 8usize],
    pub len: u32,
    pub is_write: u8,
}
impl Default for gh_vcpu_run__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gh_vcpu_run {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
