/* automatically generated by tools/bindgen-all-the-things */

#![allow(clippy::missing_safety_doc)]
#![allow(clippy::upper_case_acronyms)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Added by geniezone_sys/bindgen.sh
pub const GZVM_GET_API_VERSION: u32 = 0x00009200;
pub const GZVM_CREATE_VM: u32 = 0x00009201;
pub const GZVM_CHECK_EXTENSION: u32 = 0x00009203;
pub const GZVM_GET_VCPU_MMAP_SIZE: u32 = 0x00009204;
pub const GZVM_SET_MEMORY_REGION: u32 = 0x40189240;
pub const GZVM_CREATE_VCPU: u32 = 0x00009241;
pub const GZVM_GET_DIRTY_LOG: u32 = 0x40109242;
pub const GZVM_SET_NR_MMU_PAGES: u32 = 0x00009244;
pub const GZVM_GET_NR_MMU_PAGES: u32 = 0x00009245;
pub const GZVM_SET_USER_MEMORY_REGION: u32 = 0x40209246;
pub const GZVM_CREATE_IRQCHIP: u32 = 0x00009260;
pub const GZVM_IRQ_LINE: u32 = 0x40089261;
pub const GZVM_IRQ_LINE_STATUS: u32 = 0xc0089267;
pub const GZVM_REGISTER_COALESCED_MMIO: u32 = 0x40109267;
pub const GZVM_UNREGISTER_COALESCED_MMIO: u32 = 0x40109268;
pub const GZVM_ASSIGN_PCI_DEVICE: u32 = 0x80409269;
pub const GZVM_SET_GSI_ROUTING: u32 = 0x4008926a;
pub const GZVM_ASSIGN_DEV_IRQ: u32 = 0x40409270;
pub const GZVM_DEASSIGN_PCI_DEVICE: u32 = 0x40409272;
pub const GZVM_ASSIGN_SET_MSIX_NR: u32 = 0x40089273;
pub const GZVM_ASSIGN_SET_MSIX_ENTRY: u32 = 0x40109274;
pub const GZVM_DEASSIGN_DEV_IRQ: u32 = 0x40409275;
pub const GZVM_IRQFD: u32 = 0x40209276;
pub const GZVM_IOEVENTFD: u32 = 0x40409279;
pub const GZVM_SIGNAL_MSI: u32 = 0x402092a5;
pub const GZVM_ARM_SET_DEVICE_ADDR: u32 = 0x401092ab;
pub const GZVM_SET_PMU_EVENT_FILTER: u32 = 0x400892b2;
pub const GZVM_ARM_MTE_COPY_TAGS: u32 = 0x803092b4;
pub const GZVM_CREATE_DEVICE: u32 = 0xc03092e0;
pub const GZVM_SET_DEVICE_ATTR: u32 = 0x401892e1;
pub const GZVM_GET_DEVICE_ATTR: u32 = 0x401892e2;
pub const GZVM_HAS_DEVICE_ATTR: u32 = 0x401892e3;
pub const GZVM_RUN: u32 = 0x00009280;
pub const GZVM_GET_REGS: u32 = 0x83689281;
pub const GZVM_SET_REGS: u32 = 0x43689282;
pub const GZVM_SET_SIGNAL_MASK: u32 = 0x4004928b;
pub const GZVM_GET_MP_STATE: u32 = 0x80049298;
pub const GZVM_SET_MP_STATE: u32 = 0x40049299;
pub const GZVM_SET_GUEST_DEBUG: u32 = 0x4208929b;
pub const GZVM_GET_VCPU_EVENTS: u32 = 0x8040929f;
pub const GZVM_SET_VCPU_EVENTS: u32 = 0x404092a0;
pub const GZVM_ENABLE_CAP: u32 = 0x406892a3;
pub const GZVM_GET_ONE_REG: u32 = 0x401092ab;
pub const GZVM_SET_ONE_REG: u32 = 0x401092ac;
pub const GZVM_KVMCLOCK_CTRL: u32 = 0x000092ad;
pub const GZVM_ARM_VCPU_INIT: u32 = 0x402092ae;
pub const GZVM_ARM_PREFERRED_TARGET: u32 = 0x802092af;
pub const GZVM_GET_REG_LIST: u32 = 0xc00892b0;
pub const GZVM_MEMORY_ENCRYPT_OP: u32 = 0xc00892ba;
pub const GZVM_MEMORY_ENCRYPT_REG_REGION: u32 = 0x801092bb;
pub const GZVM_MEMORY_ENCRYPT_UNREG_REGION: u32 = 0x801092bc;
pub const GZVM_CLEAR_DIRTY_LOG: u32 = 0xc01892c0;
pub const GZVM_ARM_VCPU_FINALIZE: u32 = 0x400492c2;


#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const GIC_V3_NR_LRS: u32 = 16;
pub const GZVM_DEV_ASSIGN_ENABLE_IOMMU: u32 = 1;
pub const GZVM_DEV_ASSIGN_PCI_2_3: u32 = 2;
pub const GZVM_DEV_ASSIGN_MASK_INTX: u32 = 4;
pub const GZVM_DEV_IRQ_HOST_INTX: u32 = 1;
pub const GZVM_DEV_IRQ_GUEST_INTX: u32 = 256;
pub const GZVM_DEV_IRQ_HOST_MASK: u32 = 255;
pub const GZVM_DEV_IRQ_GUEST_MASK: u32 = 65280;
pub const GZVM_IRQ_ROUTING_IRQCHIP: u32 = 1;
pub const GZVM_IRQFD_FLAG_DEASSIGN: u32 = 1;
pub const GZVM_IRQFD_FLAG_RESAMPLE: u32 = 2;
pub const GZVM_IOC_MAGIC: u32 = 146;
pub const GZVM_MAX_MEM_REGION: u32 = 10;
pub type __le16 = u16;
pub type __be16 = u16;
pub type __le32 = u32;
pub type __be32 = u32;
pub type __le64 = u64;
pub type __be64 = u64;
pub type __sum16 = u16;
pub type __wsum = u32;
pub type __poll_t = ::std::os::raw::c_uint;
pub type u32_ = u32;
pub type u64_ = u64;
pub type u16_ = u16;
pub type u8_ = u8;
pub const GZVM_FUNC_CREATE_VM: ::std::os::raw::c_uint = 0;
pub const GZVM_FUNC_DESTROY_VM: ::std::os::raw::c_uint = 1;
pub const GZVM_FUNC_CREATE_VCPU: ::std::os::raw::c_uint = 2;
pub const GZVM_FUNC_DESTROY_VCPU: ::std::os::raw::c_uint = 3;
pub const GZVM_FUNC_SET_MEMREGION: ::std::os::raw::c_uint = 4;
pub const GZVM_FUNC_RUN: ::std::os::raw::c_uint = 5;
pub const GZVM_FUNC_GET_REGS: ::std::os::raw::c_uint = 6;
pub const GZVM_FUNC_SET_REGS: ::std::os::raw::c_uint = 7;
pub const GZVM_FUNC_GET_ONE_REG: ::std::os::raw::c_uint = 8;
pub const GZVM_FUNC_SET_ONE_REG: ::std::os::raw::c_uint = 9;
pub const GZVM_FUNC_IRQ_LINE: ::std::os::raw::c_uint = 10;
pub const GZVM_FUNC_CREATE_DEVICE: ::std::os::raw::c_uint = 11;
pub const NR_GZVM_FUNC: ::std::os::raw::c_uint = 12;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub type gzvm_id_t = u16;
pub type gzvm_vcpu_id_t = u16;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_cpu_user_regs {
    pub x0: u64,
    pub x1: u64,
    pub x2: u64,
    pub x3: u64,
    pub x4: u64,
    pub x5: u64,
    pub x6: u64,
    pub x7: u64,
    pub x8: u64,
    pub x9: u64,
    pub x10: u64,
    pub x11: u64,
    pub x12: u64,
    pub x13: u64,
    pub x14: u64,
    pub x15: u64,
    pub x16: u64,
    pub x17: u64,
    pub x18: u64,
    pub x19: u64,
    pub x20: u64,
    pub x21: u64,
    pub x22: u64,
    pub x23: u64,
    pub x24: u64,
    pub x25: u64,
    pub x26: u64,
    pub x27: u64,
    pub x28: u64,
    pub fp: u64,
    pub lr: u64,
    pub sp: u64,
    pub pc: u64,
    pub cpsr: u64,
}
pub const GZVM_EXIT_UNKNOWN: ::std::os::raw::c_uint = 2459041792;
pub const GZVM_EXIT_MMIO: ::std::os::raw::c_uint = 2459041793;
pub const GZVM_EXIT_HVC: ::std::os::raw::c_uint = 2459041794;
pub const GZVM_EXIT_IRQ: ::std::os::raw::c_uint = 2459041795;
pub const GZVM_EXIT_EXCEPTION: ::std::os::raw::c_uint = 2459041796;
pub const GZVM_EXIT_DEBUG: ::std::os::raw::c_uint = 2459041797;
pub const GZVM_EXIT_FAIL_ENTRY: ::std::os::raw::c_uint = 2459041798;
pub const GZVM_EXIT_INTERNAL_ERROR: ::std::os::raw::c_uint = 2459041799;
pub const GZVM_EXIT_SYSTEM_EVENT: ::std::os::raw::c_uint = 2459041800;
pub const GZVM_EXIT_SHUTDOWN: ::std::os::raw::c_uint = 2459041801;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_vcpu_run {
    pub exit_reason: u32,
    pub immediate_exit: u8,
    pub padding1: [u8; 3usize],
    pub __bindgen_anon_1: gzvm_vcpu_run__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_vcpu_run__bindgen_ty_1 {
    pub mmio: gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_1,
    pub fail_entry: gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_2,
    pub exception: gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_3,
    pub hvc: gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_4,
    pub internal: gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_5,
    pub system_event: gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_6,
    pub padding2: [::std::os::raw::c_char; 256usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_1 {
    pub phys_addr: u64,
    pub data: [u8; 8usize],
    pub size: u64,
    pub reg_nr: u32,
    pub is_write: bool,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_2 {
    pub hardware_entry_failure_reason: u64,
    pub cpu: u32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_3 {
    pub exception: u32,
    pub error_code: u32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_4 {
    pub args: [u64; 8usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_5 {
    pub suberror: u32,
    pub ndata: u32,
    pub data: [u64; 16usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_run__bindgen_ty_1__bindgen_ty_6 {
    pub type_: u32,
    pub flags: u64,
}
impl Default for gzvm_vcpu_run__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_vcpu_run {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_hwstate {
    pub nr_lrs: u32,
    pub lr: [u64; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_dirty_log {
    pub slot: u32,
    pub padding1: u32,
    pub __bindgen_anon_1: gzvm_dirty_log__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_dirty_log__bindgen_ty_1 {
    pub dirty_bitmap: *mut ::std::os::raw::c_void,
    pub padding2: u64,
}
impl Default for gzvm_dirty_log__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_dirty_log {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_memory_region {
    pub slot: u32,
    pub flags: u32,
    pub guest_phys_addr: u64,
    pub memory_size: u64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_userspace_memory_region {
    pub slot: u32,
    pub flags: u32,
    pub guest_phys_addr: u64,
    pub memory_size: u64,
    pub userspace_addr: u64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_irq_level {
    pub __bindgen_anon_1: gzvm_irq_level__bindgen_ty_1,
    pub level: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_irq_level__bindgen_ty_1 {
    pub irq: u32,
    pub status: i32,
}
impl Default for gzvm_irq_level__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_irq_level {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_coalesced_mmio_zone {
    pub addr: u64,
    pub size: u32,
    pub __bindgen_anon_1: gzvm_coalesced_mmio_zone__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_coalesced_mmio_zone__bindgen_ty_1 {
    pub pad: u32,
    pub pio: u32,
}
impl Default for gzvm_coalesced_mmio_zone__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_coalesced_mmio_zone {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_assigned_pci_dev {
    pub assigned_dev_id: u32,
    pub busnr: u32,
    pub devfn: u32,
    pub flags: u32,
    pub segnr: u32,
    pub __bindgen_anon_1: gzvm_assigned_pci_dev__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_assigned_pci_dev__bindgen_ty_1 {
    pub reserved: [u32; 11usize],
}
impl Default for gzvm_assigned_pci_dev__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_assigned_pci_dev {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_assigned_irq {
    pub assigned_dev_id: u32,
    pub host_irq: u32,
    pub guest_irq: u32,
    pub flags: u32,
    pub __bindgen_anon_1: gzvm_assigned_irq__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_assigned_irq__bindgen_ty_1 {
    pub reserved: [u32; 12usize],
}
impl Default for gzvm_assigned_irq__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_assigned_irq {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_irq_routing_irqchip {
    pub irqchip: u32,
    pub pin: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gzvm_irq_routing_entry {
    pub gsi: u32,
    pub type_: u32,
    pub flags: u32,
    pub pad: u32,
    pub u: gzvm_irq_routing_entry__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gzvm_irq_routing_entry__bindgen_ty_1 {
    pub irqchip: gzvm_irq_routing_irqchip,
    pub pad: [u32; 8usize],
}
impl Default for gzvm_irq_routing_entry__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for gzvm_irq_routing_entry {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct gzvm_irq_routing {
    pub nr: u32,
    pub flags: u32,
    pub entries: __IncompleteArrayField<gzvm_irq_routing_entry>,
}
impl Default for gzvm_irq_routing {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct gzvm_reg_list {
    pub n: u64,
    pub reg: __IncompleteArrayField<u64>,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_one_reg {
    pub id: u64,
    pub addr: u64,
}
pub const gzvm_ioeventfd_flag_nr_datamatch: ::std::os::raw::c_uint = 0;
pub const gzvm_ioeventfd_flag_nr_pio: ::std::os::raw::c_uint = 1;
pub const gzvm_ioeventfd_flag_nr_deassign: ::std::os::raw::c_uint = 2;
pub const gzvm_ioeventfd_flag_nr_max: ::std::os::raw::c_uint = 3;
pub type _bindgen_ty_3 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gzvm_ioeventfd {
    pub datamatch: u64,
    pub addr: u64,
    pub len: u32,
    pub fd: i32,
    pub flags: u32,
    pub pad: [u8; 36usize],
}
impl Default for gzvm_ioeventfd {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_irqfd {
    pub fd: u32,
    pub gsi: u32,
    pub flags: u32,
    pub resamplefd: u32,
    pub pad: [u8; 16usize],
}
pub const gzvm_device_type_GZVM_DEV_TYPE_ARM_VGIC_V3_DIST: gzvm_device_type = 0;
pub const gzvm_device_type_GZVM_DEV_TYPE_ARM_VGIC_V3_REDIST: gzvm_device_type = 1;
pub const gzvm_device_type_GZVM_DEV_TYPE_MAX: gzvm_device_type = 2;
pub type gzvm_device_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_create_device {
    pub dev_type: u32,
    pub id: u32,
    pub flags: u64,
    pub dev_addr: u64,
    pub dev_reg_size: u64,
    pub attr_addr: u64,
    pub attr_size: u64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gzvm_vcpu_init {
    pub target: u32,
    pub features: [u32; 7usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gzvm_arm_copy_mte_tags {
    pub guest_ipa: u64,
    pub length: u64,
    pub addr: *mut ::std::os::raw::c_void,
    pub flags: u64,
    pub reserved: [u64; 2usize],
}
impl Default for gzvm_arm_copy_mte_tags {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct mem_region_addr_range {
    pub address: u64,
    pub pg_cnt: u32,
    pub reserved: u32,
}
#[repr(C)]
#[derive(Debug, Default)]
pub struct gzvm_memory_region_ranges {
    pub slot: u32,
    pub constituent_cnt: u32,
    pub total_pages: u64,
    pub gpa: u64,
    pub constituents: __IncompleteArrayField<mem_region_addr_range>,
}
