/* automatically generated by rust-bindgen 0.60.1 */

#![allow(dead_code)]

pub const __BITS_PER_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const _IOC_NRBITS: u32 = 8;
pub const _IOC_TYPEBITS: u32 = 8;
pub const _IOC_SIZEBITS: u32 = 14;
pub const _IOC_DIRBITS: u32 = 2;
pub const _IOC_NRMASK: u32 = 255;
pub const _IOC_TYPEMASK: u32 = 255;
pub const _IOC_SIZEMASK: u32 = 16383;
pub const _IOC_DIRMASK: u32 = 3;
pub const _IOC_NRSHIFT: u32 = 0;
pub const _IOC_TYPESHIFT: u32 = 8;
pub const _IOC_SIZESHIFT: u32 = 16;
pub const _IOC_DIRSHIFT: u32 = 30;
pub const _IOC_NONE: u32 = 0;
pub const _IOC_WRITE: u32 = 1;
pub const _IOC_READ: u32 = 2;
pub const IOC_IN: u32 = 1073741824;
pub const IOC_OUT: u32 = 2147483648;
pub const IOC_INOUT: u32 = 3221225472;
pub const IOCSIZE_MASK: u32 = 1073676288;
pub const IOCSIZE_SHIFT: u32 = 16;
pub const GH_IOCTL_TYPE: u32 = 178;
pub const GH_VM_FW_NAME_MAX: u32 = 16;
pub const VBE_ASSIGN_IOEVENTFD: u32 = 1;
pub const VBE_DEASSIGN_IOEVENTFD: u32 = 2;
pub const VBE_ASSIGN_IRQFD: u32 = 1;
pub const VBE_DEASSIGN_IRQFD: u32 = 2;
pub const EVENT_NEW_BUFFER: u32 = 1;
pub const EVENT_RESET_RQST: u32 = 2;
pub const EVENT_INTERRUPT_ACK: u32 = 4;
pub const EVENT_DRIVER_OK: u32 = 8;
pub const EVENT_DRIVER_FAILED: u32 = 16;
pub const EVENT_MODULE_EXIT: u32 = 32;
pub const EVENT_VM_EXIT: u32 = 64;
pub const EVENT_APP_EXIT: u32 = 256;
pub const GH_VM_EXIT_REASON_UNKNOWN: u32 = 0;
pub const GH_VM_EXIT_REASON_SHUTDOWN: u32 = 1;
pub const GH_VM_EXIT_REASON_RESTART: u32 = 2;
pub const GH_VM_EXIT_REASON_PANIC: u32 = 3;
pub const GH_VM_EXIT_REASON_NSWD: u32 = 4;
pub const GH_VM_EXIT_REASON_HYP_ERROR: u32 = 5;
pub const GH_VM_EXIT_REASON_ASYNC_EXT_ABORT: u32 = 6;
pub const GH_VM_EXIT_REASON_FORCE_STOPPED: u32 = 7;
pub const GH_VM_EXIT_REASONS_MAX: u32 = 8;
pub const GH_VM_TYPE_ARM_PROTECTED: u32 = 1;
pub const GH_CAP_USER_MEMORY: u32 = 1;
pub const GH_CAP_ARM_PROTECTED_VM: u32 = 2;
pub const GH_CAP_ARM_VM_IPA_SIZE: u32 = 3;
pub const GH_EXIT_MMIO: u32 = 10;
pub const GH_EXIT_SHUTDOWN: u32 = 11;
pub const GH_EXIT_HLT: u32 = 12;
pub const GH_EXIT_INTR: u32 = 13;
pub const GH_EXIT_WATCHDOG: u32 = 14;
pub const GH_EXIT_SYSTEM_EVENT: u32 = 15;
pub const GH_SYSTEM_EVENT_SHUTDOWN: u32 = 1;
pub const GH_SYSTEM_EVENT_RESET: u32 = 2;
pub const GH_SYSTEM_EVENT_CRASH: u32 = 3;
pub const GH_SYSTEM_EVENT_WAKEUP: u32 = 4;
pub const GH_SYSTEM_EVENT_SUSPEND: u32 = 5;
pub const GH_IRQFD_FLAG_DEASSIGN: u32 = 1;
pub const GH_IRQFD_FLAG_RESAMPLE: u32 = 2;
pub const GH_ARM_VCPU_POWER_OFF: u32 = 0;
pub const GH_ARM_VCPU_EL1_32BIT: u32 = 1;
pub const GH_ARM_VCPU_PSCI_0_2: u32 = 2;
pub const GH_ARM_VCPU_PMU_V3: u32 = 3;
pub const GH_REG_ARM_COPROC_MASK: u32 = 268369920;
pub const GH_REG_ARM_COPROC_SHIFT: u32 = 16;
pub const GH_REG_ARM64: u64 = 6917529027641081856;
pub const GH_REG_SIZE_U64: u64 = 13510798882111488;
pub const GH_REG_ARM_CORE: u32 = 1048576;
pub const GH_ARM_TARGET_GENERIC_V8: u32 = 5;
pub const GH_NR_SPSR: u32 = 5;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
#[test]
fn bindgen_test_layout___kernel_fd_set() {
    assert_eq!(
        ::std::mem::size_of::<__kernel_fd_set>(),
        128usize,
        concat!("Size of: ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        ::std::mem::align_of::<__kernel_fd_set>(),
        8usize,
        concat!("Alignment of ", stringify!(__kernel_fd_set))
    );
    fn test_field_fds_bits() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<__kernel_fd_set>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fds_bits) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(__kernel_fd_set),
                "::",
                stringify!(fds_bits)
            )
        );
    }
    test_field_fds_bits();
}
pub type __kernel_sighandler_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_dev_t = ::std::os::raw::c_ulong;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___kernel_fsid_t() {
    assert_eq!(
        ::std::mem::size_of::<__kernel_fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__kernel_fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__kernel_fsid_t))
    );
    fn test_field_val() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<__kernel_fsid_t>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).val) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(__kernel_fsid_t),
                "::",
                stringify!(val)
            )
        );
    }
    test_field_val();
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = ::std::os::raw::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = ::std::os::raw::c_uint;
pub type __virtio16 = __u16;
pub type __virtio32 = __u32;
pub type __virtio64 = __u64;
#[doc = " @struct gh_fw_name"]
#[doc = " A structure to be passed to GH_VM_SET_FM_NAME ioctl"]
#[doc = " @name - name of the secure VM image"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_fw_name {
    pub name: [::std::os::raw::c_char; 16usize],
}
#[test]
fn bindgen_test_layout_gh_fw_name() {
    assert_eq!(
        ::std::mem::size_of::<gh_fw_name>(),
        16usize,
        concat!("Size of: ", stringify!(gh_fw_name))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_fw_name>(),
        1usize,
        concat!("Alignment of ", stringify!(gh_fw_name))
    );
    fn test_field_name() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_fw_name>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_fw_name),
                "::",
                stringify!(name)
            )
        );
    }
    test_field_name();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_ack_reset {
    pub label: __u32,
    pub reserved: __u32,
}
#[test]
fn bindgen_test_layout_virtio_ack_reset() {
    assert_eq!(
        ::std::mem::size_of::<virtio_ack_reset>(),
        8usize,
        concat!("Size of: ", stringify!(virtio_ack_reset))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_ack_reset>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_ack_reset))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_ack_reset>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_ack_reset),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_ack_reset>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_ack_reset),
                "::",
                stringify!(reserved)
            )
        );
    }
    test_field_reserved();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_driver_features {
    pub label: __u32,
    pub reserved: __u32,
    pub features_sel: __u32,
    pub features: __u32,
}
#[test]
fn bindgen_test_layout_virtio_driver_features() {
    assert_eq!(
        ::std::mem::size_of::<virtio_driver_features>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_driver_features))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_driver_features>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_driver_features))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_driver_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_driver_features),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_driver_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_driver_features),
                "::",
                stringify!(reserved)
            )
        );
    }
    test_field_reserved();
    fn test_field_features_sel() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_driver_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).features_sel) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_driver_features),
                "::",
                stringify!(features_sel)
            )
        );
    }
    test_field_features_sel();
    fn test_field_features() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_driver_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).features) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_driver_features),
                "::",
                stringify!(features)
            )
        );
    }
    test_field_features();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_queue_info {
    pub label: __u32,
    pub queue_sel: __u32,
    pub queue_num: __u32,
    pub queue_ready: __u32,
    pub queue_desc: __u64,
    pub queue_driver: __u64,
    pub queue_device: __u64,
}
#[test]
fn bindgen_test_layout_virtio_queue_info() {
    assert_eq!(
        ::std::mem::size_of::<virtio_queue_info>(),
        40usize,
        concat!("Size of: ", stringify!(virtio_queue_info))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_queue_info>(),
        8usize,
        concat!("Alignment of ", stringify!(virtio_queue_info))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_queue_sel() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_sel) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(queue_sel)
            )
        );
    }
    test_field_queue_sel();
    fn test_field_queue_num() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_num) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(queue_num)
            )
        );
    }
    test_field_queue_num();
    fn test_field_queue_ready() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_ready) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(queue_ready)
            )
        );
    }
    test_field_queue_ready();
    fn test_field_queue_desc() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_desc) as usize - ptr as usize
            },
            16usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(queue_desc)
            )
        );
    }
    test_field_queue_desc();
    fn test_field_queue_driver() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_driver) as usize - ptr as usize
            },
            24usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(queue_driver)
            )
        );
    }
    test_field_queue_driver();
    fn test_field_queue_device() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_info>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_device) as usize - ptr as usize
            },
            32usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_info),
                "::",
                stringify!(queue_device)
            )
        );
    }
    test_field_queue_device();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_config_data {
    pub label: __u32,
    pub config_size: __u32,
    pub config_data: __u64,
}
#[test]
fn bindgen_test_layout_virtio_config_data() {
    assert_eq!(
        ::std::mem::size_of::<virtio_config_data>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_config_data))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_config_data>(),
        8usize,
        concat!("Alignment of ", stringify!(virtio_config_data))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_config_data>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_config_data),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_config_size() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_config_data>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).config_size) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_config_data),
                "::",
                stringify!(config_size)
            )
        );
    }
    test_field_config_size();
    fn test_field_config_data() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_config_data>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).config_data) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_config_data),
                "::",
                stringify!(config_data)
            )
        );
    }
    test_field_config_data();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_dev_features {
    pub label: __u32,
    pub reserved: __u32,
    pub features_sel: __u32,
    pub features: __u32,
}
#[test]
fn bindgen_test_layout_virtio_dev_features() {
    assert_eq!(
        ::std::mem::size_of::<virtio_dev_features>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_dev_features))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_dev_features>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_dev_features))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_dev_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_dev_features),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_dev_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_dev_features),
                "::",
                stringify!(reserved)
            )
        );
    }
    test_field_reserved();
    fn test_field_features_sel() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_dev_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).features_sel) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_dev_features),
                "::",
                stringify!(features_sel)
            )
        );
    }
    test_field_features_sel();
    fn test_field_features() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_dev_features>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).features) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_dev_features),
                "::",
                stringify!(features)
            )
        );
    }
    test_field_features();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_queue_max {
    pub label: __u32,
    pub reserved: __u32,
    pub queue_sel: __u32,
    pub queue_num_max: __u32,
}
#[test]
fn bindgen_test_layout_virtio_queue_max() {
    assert_eq!(
        ::std::mem::size_of::<virtio_queue_max>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_queue_max))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_queue_max>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_queue_max))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_max>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_max),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_max>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_max),
                "::",
                stringify!(reserved)
            )
        );
    }
    test_field_reserved();
    fn test_field_queue_sel() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_max>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_sel) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_max),
                "::",
                stringify!(queue_sel)
            )
        );
    }
    test_field_queue_sel();
    fn test_field_queue_num_max() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_queue_max>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_num_max) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_queue_max),
                "::",
                stringify!(queue_num_max)
            )
        );
    }
    test_field_queue_num_max();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_event {
    pub label: __u32,
    pub event: __u32,
    pub event_data: __u32,
    pub reserved: __u32,
}
#[test]
fn bindgen_test_layout_virtio_event() {
    assert_eq!(
        ::std::mem::size_of::<virtio_event>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_event))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_event>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_event))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_event>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_event),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_event() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_event>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).event) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_event),
                "::",
                stringify!(event)
            )
        );
    }
    test_field_event();
    fn test_field_event_data() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_event>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).event_data) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_event),
                "::",
                stringify!(event_data)
            )
        );
    }
    test_field_event_data();
    fn test_field_reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_event>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_event),
                "::",
                stringify!(reserved)
            )
        );
    }
    test_field_reserved();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_eventfd {
    pub label: __u32,
    pub flags: __u32,
    pub queue_num: __u32,
    pub fd: __s32,
}
#[test]
fn bindgen_test_layout_virtio_eventfd() {
    assert_eq!(
        ::std::mem::size_of::<virtio_eventfd>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_eventfd))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_eventfd>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_eventfd))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_eventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_eventfd),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_eventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_eventfd),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
    fn test_field_queue_num() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_eventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).queue_num) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_eventfd),
                "::",
                stringify!(queue_num)
            )
        );
    }
    test_field_queue_num();
    fn test_field_fd() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_eventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_eventfd),
                "::",
                stringify!(fd)
            )
        );
    }
    test_field_fd();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virtio_irqfd {
    pub label: __u32,
    pub flags: __u32,
    pub fd: __s32,
    pub reserved: __u32,
}
#[test]
fn bindgen_test_layout_virtio_irqfd() {
    assert_eq!(
        ::std::mem::size_of::<virtio_irqfd>(),
        16usize,
        concat!("Size of: ", stringify!(virtio_irqfd))
    );
    assert_eq!(
        ::std::mem::align_of::<virtio_irqfd>(),
        4usize,
        concat!("Alignment of ", stringify!(virtio_irqfd))
    );
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_irqfd),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_irqfd),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
    fn test_field_fd() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_irqfd),
                "::",
                stringify!(fd)
            )
        );
    }
    test_field_fd();
    fn test_field_reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<virtio_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(virtio_irqfd),
                "::",
                stringify!(reserved)
            )
        );
    }
    test_field_reserved();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_userspace_memory_region {
    pub slot: __u32,
    pub flags: __u32,
    pub guest_phys_addr: __u64,
    pub memory_size: __u64,
    pub userspace_addr: __u64,
}
#[test]
fn bindgen_test_layout_gh_userspace_memory_region() {
    assert_eq!(
        ::std::mem::size_of::<gh_userspace_memory_region>(),
        32usize,
        concat!("Size of: ", stringify!(gh_userspace_memory_region))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_userspace_memory_region>(),
        8usize,
        concat!("Alignment of ", stringify!(gh_userspace_memory_region))
    );
    fn test_field_slot() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_userspace_memory_region>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).slot) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_userspace_memory_region),
                "::",
                stringify!(slot)
            )
        );
    }
    test_field_slot();
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_userspace_memory_region>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_userspace_memory_region),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
    fn test_field_guest_phys_addr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_userspace_memory_region>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).guest_phys_addr) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_userspace_memory_region),
                "::",
                stringify!(guest_phys_addr)
            )
        );
    }
    test_field_guest_phys_addr();
    fn test_field_memory_size() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_userspace_memory_region>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).memory_size) as usize - ptr as usize
            },
            16usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_userspace_memory_region),
                "::",
                stringify!(memory_size)
            )
        );
    }
    test_field_memory_size();
    fn test_field_userspace_addr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_userspace_memory_region>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).userspace_addr) as usize - ptr as usize
            },
            24usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_userspace_memory_region),
                "::",
                stringify!(userspace_addr)
            )
        );
    }
    test_field_userspace_addr();
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fw_name {
        pub _name: [::std::os::raw::c_char; 16usize],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_create_device {
    pub type_: __u32,
    pub fd: __u32,
    pub flags: __u32,
}
#[test]
fn bindgen_test_layout_gh_create_device() {
    assert_eq!(
        ::std::mem::size_of::<gh_create_device>(),
        12usize,
        concat!("Size of: ", stringify!(gh_create_device))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_create_device>(),
        4usize,
        concat!("Alignment of ", stringify!(gh_create_device))
    );
    fn test_field_type() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_create_device>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_create_device),
                "::",
                stringify!(type_)
            )
        );
    }
    test_field_type();
    fn test_field_fd() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_create_device>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_create_device),
                "::",
                stringify!(fd)
            )
        );
    }
    test_field_fd();
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_create_device>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_create_device),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_ioeventfd {
    pub datamatch: __u64,
    pub addr: __u64,
    pub len: __u32,
    pub fd: __s32,
    pub flags: __u32,
    pub pad: [__u8; 36usize],
}

impl Default for gh_ioeventfd {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}

#[test]
fn bindgen_test_layout_gh_ioeventfd() {
    assert_eq!(
        ::std::mem::size_of::<gh_ioeventfd>(),
        64usize,
        concat!("Size of: ", stringify!(gh_ioeventfd))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_ioeventfd>(),
        8usize,
        concat!("Alignment of ", stringify!(gh_ioeventfd))
    );
    fn test_field_datamatch() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_ioeventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).datamatch) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_ioeventfd),
                "::",
                stringify!(datamatch)
            )
        );
    }
    test_field_datamatch();
    fn test_field_addr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_ioeventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).addr) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_ioeventfd),
                "::",
                stringify!(addr)
            )
        );
    }
    test_field_addr();
    fn test_field_len() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_ioeventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).len) as usize - ptr as usize
            },
            16usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_ioeventfd),
                "::",
                stringify!(len)
            )
        );
    }
    test_field_len();
    fn test_field_fd() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_ioeventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize
            },
            20usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_ioeventfd),
                "::",
                stringify!(fd)
            )
        );
    }
    test_field_fd();
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_ioeventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            24usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_ioeventfd),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
    fn test_field_pad() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_ioeventfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).pad) as usize - ptr as usize
            },
            28usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_ioeventfd),
                "::",
                stringify!(pad)
            )
        );
    }
    test_field_pad();
}
pub const gh_device_type_GH_DEV_TYPE_ARM_VGIC_V3: gh_device_type = 1;
pub type gh_device_type = ::std::os::raw::c_uint;
pub const gh_ioeventfd_flag_nr_datamatch: _bindgen_ty_1 = 0;
pub const gh_ioeventfd_flag_nr_pio: _bindgen_ty_1 = 1;
pub const gh_ioeventfd_flag_nr_deassign: _bindgen_ty_1 = 2;
pub const gh_ioeventfd_flag_nr_fast_mmio: _bindgen_ty_1 = 3;
pub const gh_ioeventfd_flag_nr_max: _bindgen_ty_1 = 4;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gh_vcpu_run {
    pub immediate_exit: __u8,
    pub padding1: [__u8; 3usize],
    pub exit_reason: __u32,
    pub __bindgen_anon_1: gh_vcpu_run__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gh_vcpu_run__bindgen_ty_1 {
    pub mmio: gh_vcpu_run__bindgen_ty_1__bindgen_ty_1,
    pub system_event: gh_vcpu_run__bindgen_ty_1__bindgen_ty_2,
    pub padding: [::std::os::raw::c_char; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_vcpu_run__bindgen_ty_1__bindgen_ty_1 {
    pub phys_addr: __u64,
    pub data: [__u8; 8usize],
    pub len: __u32,
    pub is_write: __u8,
}
#[test]
fn bindgen_test_layout_gh_vcpu_run__bindgen_ty_1__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_1>(),
        24usize,
        concat!(
            "Size of: ",
            stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_1>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_1)
        )
    );
    fn test_field_phys_addr() {
        assert_eq!(
            unsafe {
                let uninit =
                    ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).phys_addr) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_1),
                "::",
                stringify!(phys_addr)
            )
        );
    }
    test_field_phys_addr();
    fn test_field_data() {
        assert_eq!(
            unsafe {
                let uninit =
                    ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).data) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_1),
                "::",
                stringify!(data)
            )
        );
    }
    test_field_data();
    fn test_field_len() {
        assert_eq!(
            unsafe {
                let uninit =
                    ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).len) as usize - ptr as usize
            },
            16usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_1),
                "::",
                stringify!(len)
            )
        );
    }
    test_field_len();
    fn test_field_is_write() {
        assert_eq!(
            unsafe {
                let uninit =
                    ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).is_write) as usize - ptr as usize
            },
            20usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_1),
                "::",
                stringify!(is_write)
            )
        );
    }
    test_field_is_write();
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct gh_vcpu_run__bindgen_ty_1__bindgen_ty_2 {
    pub type_: __u32,
    pub ndata: __u32,
    pub __bindgen_anon_1: gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1 {
    pub flags: __u64,
    pub data: [__u64; 16usize],
}
#[test]
fn bindgen_test_layout_gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1>(),
        128usize,
        concat!(
            "Size of: ",
            stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1)
        )
    );
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<
                    gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1,
                >::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
    fn test_field_data() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<
                    gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1,
                >::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).data) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1),
                "::",
                stringify!(data)
            )
        );
    }
    test_field_data();
}
#[test]
fn bindgen_test_layout_gh_vcpu_run__bindgen_ty_1__bindgen_ty_2() {
    assert_eq!(
        ::std::mem::size_of::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_2>(),
        136usize,
        concat!(
            "Size of: ",
            stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_2>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2)
        )
    );
    fn test_field_type() {
        assert_eq!(
            unsafe {
                let uninit =
                    ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_2>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2),
                "::",
                stringify!(type_)
            )
        );
    }
    test_field_type();
    fn test_field_ndata() {
        assert_eq!(
            unsafe {
                let uninit =
                    ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1__bindgen_ty_2>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).ndata) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1__bindgen_ty_2),
                "::",
                stringify!(ndata)
            )
        );
    }
    test_field_ndata();
}
#[test]
fn bindgen_test_layout_gh_vcpu_run__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<gh_vcpu_run__bindgen_ty_1>(),
        256usize,
        concat!("Size of: ", stringify!(gh_vcpu_run__bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_vcpu_run__bindgen_ty_1>(),
        8usize,
        concat!("Alignment of ", stringify!(gh_vcpu_run__bindgen_ty_1))
    );
    fn test_field_mmio() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).mmio) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1),
                "::",
                stringify!(mmio)
            )
        );
    }
    test_field_mmio();
    fn test_field_system_event() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).system_event) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1),
                "::",
                stringify!(system_event)
            )
        );
    }
    test_field_system_event();
    fn test_field_padding() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_run__bindgen_ty_1>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).padding) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run__bindgen_ty_1),
                "::",
                stringify!(padding)
            )
        );
    }
    test_field_padding();
}
#[test]
fn bindgen_test_layout_gh_vcpu_run() {
    assert_eq!(
        ::std::mem::size_of::<gh_vcpu_run>(),
        264usize,
        concat!("Size of: ", stringify!(gh_vcpu_run))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_vcpu_run>(),
        8usize,
        concat!("Alignment of ", stringify!(gh_vcpu_run))
    );
    fn test_field_immediate_exit() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_run>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).immediate_exit) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run),
                "::",
                stringify!(immediate_exit)
            )
        );
    }
    test_field_immediate_exit();
    fn test_field_padding1() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_run>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).padding1) as usize - ptr as usize
            },
            1usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run),
                "::",
                stringify!(padding1)
            )
        );
    }
    test_field_padding1();
    fn test_field_exit_reason() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_run>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).exit_reason) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_run),
                "::",
                stringify!(exit_reason)
            )
        );
    }
    test_field_exit_reason();
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct gh_irqfd {
    pub fd: __u32,
    pub label: __u32,
    pub flags: __u32,
    pub resamplefd: __u32,
}
#[test]
fn bindgen_test_layout_gh_irqfd() {
    assert_eq!(
        ::std::mem::size_of::<gh_irqfd>(),
        16usize,
        concat!("Size of: ", stringify!(gh_irqfd))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_irqfd>(),
        4usize,
        concat!("Alignment of ", stringify!(gh_irqfd))
    );
    fn test_field_fd() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_irqfd),
                "::",
                stringify!(fd)
            )
        );
    }
    test_field_fd();
    fn test_field_label() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).label) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_irqfd),
                "::",
                stringify!(label)
            )
        );
    }
    test_field_label();
    fn test_field_flags() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_irqfd),
                "::",
                stringify!(flags)
            )
        );
    }
    test_field_flags();
    fn test_field_resamplefd() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_irqfd>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).resamplefd) as usize - ptr as usize
            },
            12usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_irqfd),
                "::",
                stringify!(resamplefd)
            )
        );
    }
    test_field_resamplefd();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_vcpu_init {
    pub target: __u32,
    pub features: [__u32; 7usize],
}
#[test]
fn bindgen_test_layout_gh_vcpu_init() {
    assert_eq!(
        ::std::mem::size_of::<gh_vcpu_init>(),
        32usize,
        concat!("Size of: ", stringify!(gh_vcpu_init))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_vcpu_init>(),
        4usize,
        concat!("Alignment of ", stringify!(gh_vcpu_init))
    );
    fn test_field_target() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_init>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).target) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_init),
                "::",
                stringify!(target)
            )
        );
    }
    test_field_target();
    fn test_field_features() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_vcpu_init>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).features) as usize - ptr as usize
            },
            4usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_vcpu_init),
                "::",
                stringify!(features)
            )
        );
    }
    test_field_features();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gh_one_reg {
    pub id: __u64,
    pub addr: __u64,
}
#[test]
fn bindgen_test_layout_gh_one_reg() {
    assert_eq!(
        ::std::mem::size_of::<gh_one_reg>(),
        16usize,
        concat!("Size of: ", stringify!(gh_one_reg))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_one_reg>(),
        8usize,
        concat!("Alignment of ", stringify!(gh_one_reg))
    );
    fn test_field_id() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_one_reg>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).id) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_one_reg),
                "::",
                stringify!(id)
            )
        );
    }
    test_field_id();
    fn test_field_addr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_one_reg>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).addr) as usize - ptr as usize
            },
            8usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_one_reg),
                "::",
                stringify!(addr)
            )
        );
    }
    test_field_addr();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct user_pt_regs {
    pub regs: [__u64; 31usize],
    pub sp: __u64,
    pub pc: __u64,
    pub pstate: __u64,
}
#[test]
fn bindgen_test_layout_user_pt_regs() {
    assert_eq!(
        ::std::mem::size_of::<user_pt_regs>(),
        272usize,
        concat!("Size of: ", stringify!(user_pt_regs))
    );
    assert_eq!(
        ::std::mem::align_of::<user_pt_regs>(),
        8usize,
        concat!("Alignment of ", stringify!(user_pt_regs))
    );
    fn test_field_regs() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_pt_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).regs) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(user_pt_regs),
                "::",
                stringify!(regs)
            )
        );
    }
    test_field_regs();
    fn test_field_sp() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_pt_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).sp) as usize - ptr as usize
            },
            248usize,
            concat!(
                "Offset of field: ",
                stringify!(user_pt_regs),
                "::",
                stringify!(sp)
            )
        );
    }
    test_field_sp();
    fn test_field_pc() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_pt_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).pc) as usize - ptr as usize
            },
            256usize,
            concat!(
                "Offset of field: ",
                stringify!(user_pt_regs),
                "::",
                stringify!(pc)
            )
        );
    }
    test_field_pc();
    fn test_field_pstate() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_pt_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).pstate) as usize - ptr as usize
            },
            264usize,
            concat!(
                "Offset of field: ",
                stringify!(user_pt_regs),
                "::",
                stringify!(pstate)
            )
        );
    }
    test_field_pstate();
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct user_fpsimd_state {
    pub vregs: [__uint128_t; 32usize],
    pub fpsr: __u32,
    pub fpcr: __u32,
    pub __reserved: [__u32; 2usize],
}
#[test]
fn bindgen_test_layout_user_fpsimd_state() {
    assert_eq!(
        ::std::mem::size_of::<user_fpsimd_state>(),
        528usize,
        concat!("Size of: ", stringify!(user_fpsimd_state))
    );
    assert_eq!(
        ::std::mem::align_of::<user_fpsimd_state>(),
        16usize,
        concat!("Alignment of ", stringify!(user_fpsimd_state))
    );
    fn test_field_vregs() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_fpsimd_state>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).vregs) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(user_fpsimd_state),
                "::",
                stringify!(vregs)
            )
        );
    }
    test_field_vregs();
    fn test_field_fpsr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_fpsimd_state>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fpsr) as usize - ptr as usize
            },
            512usize,
            concat!(
                "Offset of field: ",
                stringify!(user_fpsimd_state),
                "::",
                stringify!(fpsr)
            )
        );
    }
    test_field_fpsr();
    fn test_field_fpcr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_fpsimd_state>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fpcr) as usize - ptr as usize
            },
            516usize,
            concat!(
                "Offset of field: ",
                stringify!(user_fpsimd_state),
                "::",
                stringify!(fpcr)
            )
        );
    }
    test_field_fpcr();
    fn test_field___reserved() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<user_fpsimd_state>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).__reserved) as usize - ptr as usize
            },
            520usize,
            concat!(
                "Offset of field: ",
                stringify!(user_fpsimd_state),
                "::",
                stringify!(__reserved)
            )
        );
    }
    test_field___reserved();
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct gh_regs {
    pub regs: user_pt_regs,
    pub sp_el1: __u64,
    pub elr_el1: __u64,
    pub spsr: [__u64; 5usize],
    pub __bindgen_padding_0: u64,
    pub fp_regs: user_fpsimd_state,
}
#[test]
fn bindgen_test_layout_gh_regs() {
    assert_eq!(
        ::std::mem::size_of::<gh_regs>(),
        864usize,
        concat!("Size of: ", stringify!(gh_regs))
    );
    assert_eq!(
        ::std::mem::align_of::<gh_regs>(),
        16usize,
        concat!("Alignment of ", stringify!(gh_regs))
    );
    fn test_field_regs() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).regs) as usize - ptr as usize
            },
            0usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_regs),
                "::",
                stringify!(regs)
            )
        );
    }
    test_field_regs();
    fn test_field_sp_el1() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).sp_el1) as usize - ptr as usize
            },
            272usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_regs),
                "::",
                stringify!(sp_el1)
            )
        );
    }
    test_field_sp_el1();
    fn test_field_elr_el1() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).elr_el1) as usize - ptr as usize
            },
            280usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_regs),
                "::",
                stringify!(elr_el1)
            )
        );
    }
    test_field_elr_el1();
    fn test_field_spsr() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).spsr) as usize - ptr as usize
            },
            288usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_regs),
                "::",
                stringify!(spsr)
            )
        );
    }
    test_field_spsr();
    fn test_field_fp_regs() {
        assert_eq!(
            unsafe {
                let uninit = ::std::mem::MaybeUninit::<gh_regs>::uninit();
                let ptr = uninit.as_ptr();
                ::std::ptr::addr_of!((*ptr).fp_regs) as usize - ptr as usize
            },
            336usize,
            concat!(
                "Offset of field: ",
                stringify!(gh_regs),
                "::",
                stringify!(fp_regs)
            )
        );
    }
    test_field_fp_regs();
}
pub type __uint128_t = u128;
