#!/bin/bash
#
# This script must be run in the location of the script!
#
# This script generates Android.bp files for this and all subdirs of this
#
DIR="${ANDROID_BUILD_TOP}/external/crosvm/seccomp"

function remove_trailing_slash {
  if [[ $1 == "/" ]]; then
    echo $i
  else
    echo ${1%/}
  fi
}

set -o errexit

function check_location() {
  local my_loc="$(realpath ${DIR})"
  my_loc=$(remove_trailing_slash ${my_loc})

  local my_pwd="$(realpath $PWD)"
  my_pwd="$(remove_trailing_slash ${my_pwd})"
  if [[ "${my_loc}" != "${my_pwd}" ]]; then
    echo ${my_loc}
    echo ${my_pwd}
    >&2 echo "the script location must be run where the script is located"
    exit 10
  fi
}

my_name=`basename $0`
seccomp_archs=("x86_64" "aarch64")

# define arch dir pattern: e.g. ${ARCH}-linux-gnu
function get_arch_dir() {
  local suffix="-linux-gnu"
  local arch=$1
  echo ${arch}${suffix}
}

# utility function to enumerate policy files
#
# 1: seccomp dir to scan
# 2: extra ls flags (e.g. to hide files)
function scan_policy_name() {
  local seccomp_dir=$1
  (
    # pushd but no output to stdout/stderr
    # the output is taken and used by the caller
    pushd $seccomp_dir > /dev/null 2>&1
    ls --hide=common_device.policy $2 -1
    popd > /dev/null 2>&1
  )
}

function gen_license() {
  local cchars=${1:-"//"}
  local year=${2:-"2020"}
cat <<EOF
${cchars} Autogenerated via ${my_name}
${cchars}
${cchars} Copyright (C) ${year} The Android Open Source Project
${cchars}
${cchars} Licensed under the Apache License, Version 2.0 (the "License");
${cchars} you may not use this file except in compliance with the License.
${cchars} You may obtain a copy of the License at
${cchars}
${cchars}      http://www.apache.org/licenses/LICENSE-2.0
${cchars}
${cchars} Unless required by applicable law or agreed to in writing, software
${cchars} distributed under the License is distributed on an "AS IS" BASIS,
${cchars} WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
${cchars} See the License for the specific language governing permissions and
${cchars} limitations under the License.

EOF
}

function gen_blueprint_boilerplate() {
cat <<EOF
genrule_defaults {
    name: "crosvm_inline_seccomp_policy_x86_64",
    cmd: "\$(location policy-inliner.sh) \$(location x86_64/common_device.policy) < \$(in) > \$(out)",
    tool_files: [
        "policy-inliner.sh",
        "x86_64/common_device.policy",
    ],
}

genrule_defaults {
    name: "crosvm_inline_seccomp_policy_aarch64",
    cmd: "\$(location policy-inliner.sh) \$(location aarch64/common_device.policy) < \$(in) > \$(out)",
    tool_files: [
        "policy-inliner.sh",
        "aarch64/common_device.policy",
    ],
}

EOF
}

#
# first two args are module type (e.g. prebuilt_usr_share_host)
# and the whitespaces for indentation
#
# the rest must be in this form:
#  --name=value
#
# then, it simply generates this line repeatedly:
# <indent>name: value,
#
# e.g. --name="\"foo\"" will generate
#   name: "foo",
#
function gen_module() {
  local mod_name=$1  # e.g. prebuilt_usr_share_host
  local indent="$2"
  shift 2
  local long_options=()
  local long_opt=""
  local OPTIND=1
  while getopts ":-:" op; do
    # a long opt like --srcs="some" is actually:
    # - + - + "srcs=some"
    # that's a short option '-' just like h, and
    # the OPTARGS of the option '-' is srcs=some 
    if [[ "$op" != "-" ]]; then
      >&2 echo "gen_module does take long options with = only"
      exit 8
    fi
    long_op="${OPTARG%%=*}"
    OPTARG="${OPTARG#$long_op}"
    OPTARG="${OPTARG#=}"
    long_options+=( "$long_op" )
    declare local ${long_op}="${OPTARG}"
  done

  echo "$mod_name {"
  for field in "${long_options[@]}"; do
    eval local value=\$$field
    echo "${indent}${field}: ${value},"
  done
  echo "}"
}

function gen_blueprint_arch_policy_files() {
  local arch="$1"
  local arch_dir="$(get_arch_dir ${arch})"
  local seccomp_dir="${arch}"
  local where_in_etc_on_user_machine="crosvm/${arch_dir}/seccomp"
  echo "// ${arch}"
  echo
  for i in $(scan_policy_name ${seccomp_dir} --hide=common_device.frequency); do
    # first two are: e.g. genrule and whitespace for intentation
    local base_name="$(basename $i)"
    gen_module "genrule" '    ' \
      --name="\"${base_name}_at_${arch}\"" \
      --defaults="[\"crosvm_inline_seccomp_policy_${arch}\"]" \
      --srcs="[\"${arch}/${base_name}\"]" \
      --out="[\"${where_in_etc_on_user_machine}/${base_name}\"]"
    echo
  done
}

function gen_host_package_mk_arch_fragment() {
  local arch="$1"
  local arch_dir="$(get_arch_dir ${arch})"
  local seccomp_dir="${arch}"
  local where_in_etc_on_user_machine="crosvm/${arch_dir}/seccomp"
  echo "crosvm_inline_seccomp_policy_${arch} := \\"
  for i in $(scan_policy_name ${seccomp_dir}); do
    local base_name="$(basename $i)"
    echo '    ' \
      ${where_in_etc_on_user_machine}/${base_name} \\
  done
  echo
}

# main
check_location
gen_license >Android.bp
gen_license \# >host_package.mk
gen_blueprint_boilerplate >>Android.bp
for arch in ${seccomp_archs[@]}; do
  gen_blueprint_arch_policy_files ${arch} >>Android.bp
  gen_host_package_mk_arch_fragment ${arch} >>host_package.mk
done
