#!/bin/bash

export LD_PRELOAD=libdrm.so.2
#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/mnt/build/aosp/out/host/linux-x86/lib64"
#export LD_PRELOAD="/mnt/build/aosp/prebuilts/clang/host/linux-x86/clang-r487747/lib/clang/17/lib/linux/libclang_rt.tsan-x86_64.so:libdrm.so.2"
exec "$(dirname "$0")/$(uname -m)-linux-gnu/$(basename "$0")" "${@}"
